export const countryCodes = [
  {"code":"+001","country":"United States"},
  {"code":"+093","country":"Afghanistan"},
  {"code":"+355","country":"Albania"},
  {"code":"+376","country":"Andorra"},
  {"code":"+244","country":"Angola"},
  {"code":"+001","country":"Anguilla"},
  {"code":"+672","country":"Antarctica"},
  {"code":"+001","country":"Antigua & Barbuda"},
  {"code":"+054","country":"Argentina"},
  {"code":"+374","country":"Armenia"},
  {"code":"+297","country":"Aruba"},
  {"code":"+247","country":"Ascension Island"},
  {"code":"+061","country":"Australia"},
  {"code":"+043","country":"Austria"},
  {"code":"+994","country":"Azerbaijan"},
  {"code":"+001","country":"Bahamas"},
  {"code":"+973","country":"Bahrain"},
  {"code":"+880","country":"Bangladesh"},
  {"code":"+001","country":"Barbados"},
  {"code":"+375","country":"Belarus"},
  {"code":"+032","country":"Belgium"},
  {"code":"+501","country":"Belize"},
  {"code":"+229","country":"Benin"},
  {"code":"+001","country":"Bermuda"},
  {"code":"+975","country":"Bhutan"},
  {"code":"+591","country":"Bolivia"},
  {"code":"+387","country":"Bosnia & Herzegovina"},
  {"code":"+267","country":"Botswana"},
  {"code":"+055","country":"Brazil"},
  {"code":"+246","country":"British Indian Ocean Territory"},
  {"code":"+673","country":"Brunei"},
  {"code":"+359","country":"Bulgaria"},
  {"code":"+226","country":"Burkina Faso"},
  {"code":"+257","country":"Burundi"},
  {"code":"+238","country":"Cabo Verde"},
  {"code":"+855","country":"Cambodia"},
  {"code":"+237","country":"Cameroon"},
  {"code":"+001","country":"Canada"},
  {"code":"+001","country":"Cayman Islands"},
  {"code":"+236","country":"Central African Republic"},
  {"code":"+235","country":"Chad"},
  {"code":"+056","country":"Chile"},
  {"code":"+086","country":"China"},
  {"code":"+061","country":"Christmas Island"},
  {"code":"+061","country":"Cocos (Keeling) Islands"},
  {"code":"+057","country":"Colombia"},
  {"code":"+269","country":"Comoros"},
  {"code":"+242","country":"Congo - Brazzaville"},
  {"code":"+243","country":"Congo - Kinshasa"},
  {"code":"+682","country":"Cook Islands"},
  {"code":"+506","country":"Costa Rica"},
  {"code":"+385","country":"Croatia"},
  {"code":"+053","country":"Cuba"},
  {"code":"+599","country":"Curaçao"},
  {"code":"+357","country":"Cyprus"},
  {"code":"+420","country":"Czechia"},
  {"code":"+225","country":"Côte d'Ivoire"},
  {"code":"+045","country":"Denmark"},
  {"code":"+253","country":"Djibouti"},
  {"code":"+001","country":"Dominica"},
  {"code":"+001","country":"Dominican Republic"},
  {"code":"+593","country":"Ecuador"},
  {"code":"+020","country":"Egypt"},
  {"code":"+503","country":"El Salvador"},
  {"code":"+240","country":"Equatorial Guinea"},
  {"code":"+291","country":"Eritrea"},
  {"code":"+372","country":"Estonia"},
  {"code":"+268","country":"Eswatini"},
  {"code":"+251","country":"Ethiopia"},
  {"code":"+500","country":"Falkland Islands"},
  {"code":"+298","country":"Faroe Islands"},
  {"code":"+679","country":"Fiji"},
  {"code":"+358","country":"Finland"},
  {"code":"+033","country":"France"},
  {"code":"+594","country":"French Guiana"},
  {"code":"+689","country":"French Polynesia"},
  {"code":"+262","country":"French Southern Territories"},
  {"code":"+241","country":"Gabon"},
  {"code":"+220","country":"Gambia"},
  {"code":"+995","country":"Georgia"},
  {"code":"+049","country":"Germany"},
  {"code":"+233","country":"Ghana"},
  {"code":"+350","country":"Gibraltar"},
  {"code":"+030","country":"Greece"},
  {"code":"+299","country":"Greenland"},
  {"code":"+001","country":"Grenada"},
  {"code":"+590","country":"Guadeloupe"},
  {"code":"+001","country":"Guam"},
  {"code":"+502","country":"Guatemala"},
  {"code":"+044","country":"Guernsey"},
  {"code":"+224","country":"Guinea"},
  {"code":"+245","country":"Guinea-Bissau"},
  {"code":"+592","country":"Guyana"},
  {"code":"+509","country":"Haiti"},
  {"code":"+672","country":"Heard & McDonald Islands"},
  {"code":"+504","country":"Honduras"},
  {"code":"+852","country":"Hong Kong SAR China"},
  {"code":"+036","country":"Hungary"},
  {"code":"+354","country":"Iceland"},
  {"code":"+091","country":"India"},
  {"code":"+062","country":"Indonesia"},
  {"code":"+098","country":"Iran"},
  {"code":"+964","country":"Iraq"},
  {"code":"+353","country":"Ireland"},
  {"code":"+044","country":"Isle of Man"},
  {"code":"+972","country":"Israel"},
  {"code":"+039","country":"Italy"},
  {"code":"+001","country":"Jamaica"},
  {"code":"+081","country":"Japan"},
  {"code":"+044","country":"Jersey"},
  {"code":"+962","country":"Jordan"},
  {"code":"+007","country":"Kazakhstan"},
  {"code":"+254","country":"Kenya"},
  {"code":"+686","country":"Kiribati"},
  {"code":"+383","country":"Kosovo"},
  {"code":"+965","country":"Kuwait"},
  {"code":"+996","country":"Kyrgyzstan"},
  {"code":"+856","country":"Laos"},
  {"code":"+371","country":"Latvia"},
  {"code":"+961","country":"Lebanon"},
  {"code":"+266","country":"Lesotho"},
  {"code":"+231","country":"Liberia"},
  {"code":"+218","country":"Libya"},
  {"code":"+423","country":"Liechtenstein"},
  {"code":"+370","country":"Lithuania"},
  {"code":"+352","country":"Luxembourg"},
  {"code":"+853","country":"Macao SAR China"},
  {"code":"+261","country":"Madagascar"},
  {"code":"+265","country":"Malawi"},
  {"code":"+060","country":"Malaysia"},
  {"code":"+960","country":"Maldives"},
  {"code":"+223","country":"Mali"},
  {"code":"+356","country":"Malta"},
  {"code":"+692","country":"Marshall Islands"},
  {"code":"+596","country":"Martinique"},
  {"code":"+222","country":"Mauritania"},
  {"code":"+230","country":"Mauritius"},
  {"code":"+262","country":"Mayotte"},
  {"code":"+052","country":"Mexico"},
  {"code":"+691","country":"Micronesia"},
  {"code":"+373","country":"Moldova"},
  {"code":"+377","country":"Monaco"},
  {"code":"+976","country":"Mongolia"},
  {"code":"+382","country":"Montenegro"},
  {"code":"+001","country":"Montserrat"},
  {"code":"+212","country":"Morocco"},
  {"code":"+258","country":"Mozambique"},
  {"code":"+095","country":"Myanmar (Burma)"},
  {"code":"+264","country":"Namibia"},
  {"code":"+674","country":"Nauru"},
  {"code":"+977","country":"Nepal"},
  {"code":"+031","country":"Netherlands"},
  {"code":"+687","country":"New Caledonia"},
  {"code":"+064","country":"New Zealand"},
  {"code":"+505","country":"Nicaragua"},
  {"code":"+227","country":"Niger"},
  {"code":"+234","country":"Nigeria"},
  {"code":"+683","country":"Niue"},
  {"code":"+672","country":"Norfolk Island"},
  {"code":"+850","country":"North Korea"},
  {"code":"+001","country":"Northern Mariana Islands"},
  {"code":"+047","country":"Norway"},
  {"code":"+968","country":"Oman"},
  {"code":"+092","country":"Pakistan"},
  {"code":"+680","country":"Palau"},
  {"code":"+970","country":"Palestinian Territories"},
  {"code":"+507","country":"Panama"},
  {"code":"+675","country":"Papua New Guinea"},
  {"code":"+595","country":"Paraguay"},
  {"code":"+051","country":"Peru"},
  {"code":"+063","country":"Philippines"},
  {"code":"+064","country":"Pitcairn Islands"},
  {"code":"+048","country":"Poland"},
  {"code":"+351","country":"Portugal"},
  {"code":"+001","country":"Puerto Rico"},
  {"code":"+974","country":"Qatar"},
  {"code":"+262","country":"Réunion"},
  {"code":"+040","country":"Romania"},
  {"code":"+007","country":"Russia"},
  {"code":"+250","country":"Rwanda"},
  {"code":"+590","country":"Saint Barthélemy"},
  {"code":"+290","country":"Saint Helena"},
  {"code":"+001","country":"Saint Kitts & Nevis"},
  {"code":"+001","country":"Saint Lucia"},
  {"code":"+590","country":"Saint Martin"},
  {"code":"+508","country":"Saint Pierre & Miquelon"},
  {"code":"+685","country":"Samoa"},
  {"code":"+378","country":"San Marino"},
  {"code":"+239","country":"Sao Tomé & Príncipe"},
  {"code":"+966","country":"Saudi Arabia"},
  {"code":"+221","country":"Senegal"},
  {"code":"+381","country":"Serbia"},
  {"code":"+248","country":"Seychelles"},
  {"code":"+232","country":"Sierra Leone"},
  {"code":"+065","country":"Singapore"},
  {"code":"+001","country":"Sint Maarten"},
  {"code":"+421","country":"Slovakia"},
  {"code":"+386","country":"Slovenia"},
  {"code":"+677","country":"Solomon Islands"},
  {"code":"+252","country":"Somalia"},
  {"code":"+027","country":"South Africa"},
  {"code":"+500","country":"South Georgia & South Sandwich Islands"},
  {"code":"+082","country":"South Korea"},
  {"code":"+211","country":"South Sudan"},
  {"code":"+034","country":"Spain"},
  {"code":"+094","country":"Sri Lanka"},
  {"code":"+249","country":"Sudan"},
  {"code":"+597","country":"Suriname"},
  {"code":"+047","country":"Svalbard & Jan Mayen"},
  {"code":"+046","country":"Sweden"},
  {"code":"+041","country":"Switzerland"},
  {"code":"+963","country":"Syria"},
  {"code":"+886","country":"Taiwan"},
  {"code":"+992","country":"Tajikistan"},
  {"code":"+255","country":"Tanzania"},
  {"code":"+066","country":"Thailand"},
  {"code":"+670","country":"Timor-Leste"},
  {"code":"+228","country":"Togo"},
  {"code":"+690","country":"Tokelau"},
  {"code":"+676","country":"Tonga"},
  {"code":"+001","country":"Trinidad & Tobago"},
  {"code":"+216","country":"Tunisia"},
  {"code":"+090","country":"Turkey"},
  {"code":"+993","country":"Turkmenistan"},
  {"code":"+001","country":"Turks & Caicos Islands"},
  {"code":"+688","country":"Tuvalu"},
  {"code":"+256","country":"Uganda"},
  {"code":"+380","country":"Ukraine"},
  {"code":"+971","country":"United Arab Emirates"},
  {"code":"+044","country":"United Kingdom"},
  {"code":"+598","country":"Uruguay"},
  {"code":"+998","country":"Uzbekistan"},
  {"code":"+678","country":"Vanuatu"},
  {"code":"+379","country":"Vatican City"},
  {"code":"+058","country":"Venezuela"},
  {"code":"+084","country":"Vietnam"},
  {"code":"+681","country":"Wallis & Futuna"}
];
